on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    container: sandrolexform3/gh-runner:builder
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        
      # Use the output from the `hello` step
      - name: Verify
        run: |
          ls -al 
          ls -al /__w/_temp
      - name: tool-one
        run: /__w/_temp/tool-one.sh

      - name: tool-two
        run: /__w/_temp/tool-two.sh